### ISSUE TITLE
UI overlapping while generating addresses on iPhone SE

### ISSUE THREAD

**Issue by pozilei** [l3wi/iotaMobile#1]
Hello, 

as you generate new addresses and attach them to the tangle, the information about it is overlapping with the shown balance. screenshot attached

![img_2434](https://user-images.githubusercontent.com/24463053/27579002-4a5edb2a-5b26-11e7-965d-59b245d167ac.PNG)

**Comment by l3wi** [comment]
Thanks for noting that! 

I'll look at providing better support for smaller screens in the next few updates.

**Comment by l3wi** [comment]
Fixed, to be released in the next build.

Closing for now. Reopen if it persists
