### ISSUE TITLE
Denying access to the camera after clicking the QR icon crashes the app

### ISSUE THREAD

**Issue by geminoz** [l3wi/iotaMobile#14]
I think the title says most of it. To reproduce.

- open the app and login
- select 'send'
- if it's the first time the app is requesting permission to access the camera 
-- click the QR icon
-- deny access and the app crashes
- if it's the permission to access the camera has already been denied
-- click the QR icon and the app crashes

I believe to temporarily solve this someone would need to remove and install the app again. I have not tried that myself tho.

Expected behaviour:

- the app should be able to handle permissions and gracefully report the user what to do in case access to the camera has been denied.

**Comment by nicoschtein** [comment]
I can reproduce, thanks for reporting.

**Comment by l3wi** [comment]
Issue has been handled and will be pushed in the next build.

If the error persists then please repon the issue
