### ISSUE TITLE
Runtime error while trying to run in iOS simulator

### ISSUE THREAD

**Issue by pRizz** [l3wi/iotaMobile#3]
I followed the instructions in the readme and it compiles, but there is this error at runtime. Ran in iPhone 7 and SE simulators, Xcode 8.3.3.

![simulator screen shot jun 27 2017 1 28 36 pm](https://user-images.githubusercontent.com/3519085/27603790-e2d9ae96-5b3c-11e7-9698-fa28f2c3ec93.png)

**Comment by l3wi** [comment]
Hey this is a known issue. 

For a work around please press cmd + D and debug remotely.

**Comment by JensC** [comment]
Thanks. This should be in the README.md.
