### ISSUE TITLE
"Attach to Tangle" dissapears after switching tabs 

### ISSUE THREAD

**Issue by Schlitten** [l3wi/iotaMobile#5]
Following Process:

"Receive Tab" - "press Generate Address" - "switch to Transaction Tab" - "switch to Receive Tab"

When I press "Generate Address" the button switches to "Attach to Tangle". After switching
to Transaction Tab and switching back to Receive Tab the Button is now "Generate Address" again
although generating the Address is not finished yet. When the generation is finished there is still the button "Generate Address".

That means I can not attach the Address that I just generated to the tangle? Anyone else experiencing the same issue?

iPhone 5s iOS 10.3.3

**Comment by l3wi** [comment]
This is due to a local state which doesn't persist across views. 

Adding this flag to the redux store will fix this.

**Comment by l3wi** [comment]
Fixed, to be released in the next build.

Closing for now. Reopen if it persists
