### ISSUE TITLE
Button Position "Attach to Tangle" & "Generate new Address" in "Receive" Tab

### ISSUE THREAD

**Issue by Schlitten** [l3wi/iotaMobile#7]
The "Attach to Tangle" & "Generate new Address" Button is on the very bottom (when QR code is present). I Would prefer some space between the bottom of the button and the bottom of my screen.

Just my opinion :)

**Comment by l3wi** [comment]
Can you please attach a screenshot of the screen you are talking about?

**Comment by nicoschtein** [comment]
Please include your phone model and iOS version. 

N I C O

**Comment by Schlitten** [comment]
![](http://i.imgur.com/pxhc4Q7.jpg)

iPhone 5s iOS 10.3.3

so there is no space between the bottom of the button and the end of my screen. Hope you get what I mean :)

**Comment by l3wi** [comment]
I understand. 

There is no margin bottom on the buttons there. Thats a simple css fix.

**Comment by l3wi** [comment]
Fixed, to be released in the next build.

Closing for now. Reopen if it persists
