### ISSUE TITLE
On an iPhone 5/5s/SE sized phone, the 'repeat password' field is covered by the keyboard

### ISSUE THREAD

**Issue by geminoz** [l3wi/iotaMobile#9]
Steps to reproduce:

- open the app and tap 'load new wallet'
- tap on 'repeat password' (or 'enter seed' and 'enter a complex password' first, but it's not necessary)

Result:

- the 'repeat password' field is hidden by the system keyboard, as per screenshot. Typing would insert the password in the field, but the user experience is not optimal.

Intended result:

- the page should probably scroll up a little, allowing the user to see what's being typed in the 'repeat password' field.

![img_0245](https://user-images.githubusercontent.com/6466212/27633670-811d8fd0-5c43-11e7-8575-683542bb8830.PNG)

**Comment by l3wi** [comment]
Fixed, to be released in the next build.

Closing for now. Reopen if it persists
